# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Udmurt spellchecker"
udm = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Udmurt, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
udm = "TRANSLATE: A spellchecker for Udmurt, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.udm"

[windows]
system_product_code = "{BA641582-AB09-4D42-968A-756DDD47977B}_is1"
legacy_product_codes = [
    { value = "A20956EC-901B-4AC8-9CD3-D8897920B4E5", kind = "nsis" },
    { value = "4D7249A1-5B73-40A2-832C-FD79D62BF15E", kind = "nsis" }
]

[package.speller]
name = "Udmurt"
version = "0.1.1"

[package.grammar]
name = "Udmurt"
version = "0.1.0"

[package.tts-text-proc]
name = "Udmurt"
version = "0.1.0"
