template = "https://github.com/giellalt/template-lang-und"
rev_id = 120
template_sha = "d6eda89db0a3f76f20eb59ac36cf31cc6ed38dca"

[replacements]
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
