template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "7b8a6c39a9307995ad9926ecd5b777ca888b3659"

[replacements]
__GLOTTOLOG_ID__ = "udmu1245"
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
