template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "udmu1245"
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
