template = "https://github.com/giellalt/template-lang-und"
rev_id = 251
template_sha = "fb831d8496f6207a123362fece622ed5e22ef617"

[replacements]
__GLOTTOLOG_ID__ = "udmu1245"
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
