template = "https://github.com/giellalt/template-lang-und"
rev_id = 146
template_sha = "98e511b39680f6ce1ef730eb45be929b6d25b480"

[replacements]
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
